### PR TITLE
Revisions for current intake-esm

### PR DESCRIPTION
**Pull request by ktyle**
This PR updates the `notebooks/foundations/enhanced-catalog` notebook to resolve various errors related to changes in the underlying `intake` and `intake-esm` libraries. Also took an opportunity to refresh the content a bit, based on current examples in https://intake-esm.readthedocs.io/en/stable/index.html .

### CODE REVIEW

**Comment by ktyle** [comment]
The build is failing but that is due to as-yet unresolved issues with the `example-workflows/key-figures` notebook.

**Comment by brian-rose** [comment]
@ktyle thanks for opening this! I'll take a look at the notebook tonight.

It seems that your PR commits the output of the `enhanced-catalog.ipynb` notebook. That's handy for now so I can easily look at it, but is it violating the spirit of our push for reproducible notebooks? Should we always strip output before committing and let the CI system do the execution (as we enforce for Foundations)?

I'm not sure we ever came up with a clear policy about this for the Cookbooks.

**Comment by ktyle** [comment]
Yes, I should have cleared the output before committing. Although I think we should have an exception for #3 ...

**Review by brian-rose — APPROVED** [review]
@ktyle I pushed a new commit that cleared the output.

Before doing this, I verified that the notebook runs cleanly on my own system. I also see that it ran cleanly on our CI system.

I really like the modifications to this notebook! Everything reads well and is clearer than the original.

I suggest we merge this update, and then open a new PR to deal with #3

**Comment by brian-rose** [comment]
I think that if we merge this, the update will *not* get published because of the build failure related to #3.

A short-term solution, as discussed in #3, is to commit a copy of the `key-figures` notebook that contains locally-rendered output.

But we will also have to change the execution settings in the `config` file to a format that will *not* try to execute that notebook.

e.g. change `execute_notebooks: binder` to `execute_notebooks: auto`
(which will not try to execute a notebook [that does not have missing output](https://jupyterbook.org/en/stable/content/execute.html#trigger-notebook-execution))

**Comment by ktyle** [comment]
hmmm I wonder if there is a more granular way in jupyterbook to "opt out" certain notebooks from being executed.

But in this case, since there are just two notebooks in the cookbook, setting the flag to "auto" seems reasonable. I propose we merge this PR, and then create a new PR that contains the fully-executed key-figures notebook and also switches the build flag to auto.

**Pull request merged**
