### PR TITLE
doi infrastructure changes

### PR DESCRIPTION
**Pull request by jukent**
Match template with Zenodo badges, how to cite page, etc

### CODE REVIEW

**Comment by jukent** [comment]
Link checker will fail until we've activated Zenodo releases, which we want to do after the CITATION.cff file has been added.

**Comment by jukent** [comment]
What are your ORCID's @bonnland @jeffdlb @scottyhq @andersy005 ?

**Comment by bonnland** [comment]
I currently don't have an ORCID.   If it's recommended for NCAR employees, I can arrange to get one.

**Comment by scottyhq** [comment]
https://orcid.org/0000-0003-0624-4965 thanks for notebooks alive @jukent !

**Comment by jukent** [comment]
@bonnland you do not need one, but it is a great tool for keeping track of publications and getting credit. If you decide to make one we'll add it in.

**Comment by jeffdlb** [comment]
See below for ORCID!

J-F de La Beaujardiere, PhD
Former Director, NCAR/CISL Information Systems Division
https://staff.ucar.edu/users/jeffdlb
https://orcid.org/0000-0002-1001-9210

**Pull request merged**
