### PR TITLE
Pre-ran key-figures.ipynb; change JB execution to auto

### PR DESCRIPTION
**Pull request by ktyle**
Addresses #3 . Let's see if everything builds properly ... the fully-run key-figures notebook should not get re-run since Jupyter Book execution is set to auto.

### CODE REVIEW

**Comment by ktyle** [comment]
Yay it ran! But I will need to re-run locally, since I had interrupted one of the (long) Dask compute cells after mistakenly re-running it. I also will add some Markdown warning users who want to run it on their own that the notebook will take a long time to run.

**Comment by ktyle** [comment]
<sigh>looks like NCAR just changed some URL's! New one for LENS CESM looks to be https://www.cesm.ucar.edu/community-projects/lens

**Review by r-ford — APPROVED** [review]
Besides the one interrupted cell, looks good!

**Comment by brian-rose** [comment]
Is that interrupted cell supposed to be there? I'm a bit confused about that.

**Comment by ktyle** [comment]
Thought I had pushed the version that had the interrupted cell resolved. I will try again ...

**Comment by ktyle** [comment]
My guess is that this may be an unintended misbehavior in Jupyterbook with the `execute=auto` flag. Since the previous commit had output in all the cells, even though the newer commit is different, Jupyterbook is not updating the HTML file.

**Comment by brian-rose** [comment]
> My guess is that this may be an unintended misbehavior in Jupyterbook with the `execute=auto` flag. Since the previous commit had output in all the cells, even though the newer commit is different, Jupyterbook is not updating the HTML file.

hmm you may be right.

There's another possible strategy: We can specific particular files to be excluded from execution at build time:
https://jupyterbook.org/en/stable/content/execute.html#exclude-files-from-execution

Maybe if we set `execute_notebooks: force` but add the beefy notebook to the exclude list, we will finally get the desired behavior.

**Comment by ktyle** [comment]
Could be ... wonder if that will either:

1. update the previously-rendered HTML
2. Not update the previously-rendered HTML (same misbehavior as with `auto`), or
3. Remove the previously-rendered HTML leaving nothing in its place

I think I'll try building the book locally to see what happens before pushing. Otherwise, seems the only option would be to do a push where the notebook is temporarily removed, then add it back and push again.

**Comment by ktyle** [comment]
Oh yeah I see it now on the preview as well! I was too impatient I guess. I will merge! 😺

**Comment by brian-rose** [comment]
> Oh yeah I see it now on the preview as well! I was too impatient I guess. I will merge! 😺

Correction, thanks for your *catted* efforts on this.

**Comment by ktyle** [comment]
😹

**Pull request merged**
