### PR TITLE
Use binder -- can we run the big notebook?

### LINKED ISSUE #3: Calculations in `key-figures.ipynb` take too long
Similar to [this issue in the CMIP6 Cookbook](https://github.com/ProjectPythiaCookbooks/cmip6-cookbook/issues/18), `key-figures.ipynb` is too much for GitHub Actions to build, so the cell outputs are not included. In this case, though, I can't just cut out some material.

I'm not sure that Dask is actually implemented properly in this notebook, so a solution to this issue could just be using Dask to speed up the computation.

### PR DESCRIPTION
**Pull request by brian-rose**
Does the new Pythia binder resolve #3 ?

### CODE REVIEW

**Comment by brian-rose** [comment]
The build is erroring out with 
```
asyncio.exceptions.TimeoutError
```
same as I found over at https://github.com/ProjectPythia/na-cordex-viz-cookbook/pull/4

I guess there is a timeout limit specfied somewhere, I will investigate.

**Comment by ktyle** [comment]
It looks like some additional infrastructre is necessary in order to provide Dask capabilities.  https://www.zonca.dev/posts/2022-04-04-dask-gateway-jupyterhub.html

**Comment by brian-rose** [comment]
Yes, the binderbot CLI has an input option `--nb-timeout` [that defaults to 600 seconds](https://github.com/pangeo-gallery/binderbot/blob/32c96df4f56857bb1c4f7676ef9323a173aed677/binderbot/cli.py#L29).

We don't currently have an option to modify this default in our build workflow, but I will add this.

**Comment by brian-rose** [comment]
> It looks like some additional infrastructre is necessary in order to provide Dask capabilities. https://www.zonca.dev/posts/2022-04-04-dask-gateway-jupyterhub.html

Both this notebook and the one in https://github.com/ProjectPythia/na-cordex-viz-cookbook run interactively on the Pythia binder, they just take a while.

Both notebooks use Dask but only with distributed.LocalCluster.

Using Dask Gateway to dynamically spin up big worker clusters would be a big asset, but it seems like there are some technical barriers to implementing this capability on JetStream2. We budgeted to develop this capability in our under-review NSF grant.

**Comment by brian-rose** [comment]
Fixed one obsolete bit of code that raised exceptions during interactive run.

Set a new flag to allow notebook execution up to one hour on the binder.

Changed the cron schedule for the `nightly-build.yaml` to weekly rather than nightly.

Let's see if this builds successfully!

**Comment by brian-rose** [comment]
If this works, then we can close #3

**Comment by brian-rose** [comment]
Yay, it works!

**Comment by brian-rose** [comment]
@ktyle @r-ford any comments before merging this?

The cookbook is now fully reproducing.

**Review by ktyle — APPROVED** [review]

**Pull request merged**
