### PR TITLE
Go back to building on binder

### PR DESCRIPTION
**Pull request by brian-rose**
Should speed up the build time

### CODE REVIEW

**Comment by brian-rose** [comment]
There's something wrong with the Binder image. It did not build a new image after the environment file was updated in #30. On interactive use, the binder kernel is dying immediately.

**Comment by ktyle** [comment]
@brian-rose I noticed that the kernel still crashes ... it occurs immediately upon imports of various essential packages, such as xarray and pandas. I'm going to try triggering a new docker image build and troubleshoot from there.

**Comment by ktyle** [comment]
Still crashing. Next I'm going to try specifying a Python 3.11-based environment.

**Comment by brian-rose** [comment]
Seeing what happens with the latest binder image, which I just noted seems to be working interactively.

**Comment by brian-rose** [comment]
This is working now, and cuts the build time to 43 minutes relative to 1h15min running on GitHub.

**Pull request merged**
